'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddChiendich

    '''<summary>
    '''txt_Tenchuongtrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Tenchuongtrinh As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''de_Ngaybatdau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents de_Ngaybatdau As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''de_Ngayketthuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents de_Ngayketthuc As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''cb_TagSP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_TagSP As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txt_mota2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mota2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btn_Refresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Refresh As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Add As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Phat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Phat As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Thu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Thu As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''cb_Trangthai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Trangthai As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dgvDevexpress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDevexpress2 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''dgv1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgv1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
