'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddChiendich_Dungthu

    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''txt_Tenchuongtrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Tenchuongtrinh As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ck_Trangthai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ck_Trangthai As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''cb_Khachhang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Khachhang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''de_Ngayphat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents de_Ngayphat As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''cb_Sanpham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Sanpham As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''de_Ngayketthuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents de_Ngayketthuc As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''btn_Refresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Refresh As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Add As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dgvDevexpress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDevexpress As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''cb_TenCT_Load control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_TenCT_Load As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dgv_Ds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgv_Ds As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
