'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddWork

    '''<summary>
    '''btnQuaylai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuaylai As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ltrTitleHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTitleHeader As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''upCongviec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upCongviec As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtHotenKH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHotenKH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''deNgaylam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deNgaylam As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtGhichuCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGhichuCV As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ltrErrorCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrErrorCV As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrSuccessCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrSuccessCV As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ddlTukhoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTukhoa As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''dgvTukhoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvTukhoa As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''btnOkCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOkCV As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnLammoiCV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLammoiCV As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dgvCongviec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvCongviec As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''UpdateProgress2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress2 As Global.System.Web.UI.UpdateProgress
End Class
