'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomerCasev2

    '''<summary>
    '''pcChamsockhachhang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcChamsockhachhang As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''cboTrangthai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTrangthai As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Grv_KHTiemnag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grv_KHTiemnag As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
