'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ThuVoucher

    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''txt_MaVoucher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_MaVoucher As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txt_Tenchuongtrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Tenchuongtrinh As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txt_Menhgia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Menhgia As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txt_Ngaybatdau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Ngaybatdau As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txt_Ngayketthuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Ngayketthuc As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txt_MaKH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_MaKH As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txt_TenKH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_TenKH As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txt_Ngayphat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Ngayphat As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''btn_Tim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Tim As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Add As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lbl_Alert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Alert As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ck_Trangthai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ck_Trangthai As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''dgvDevexpress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDevexpress As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
