'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Loyalty_Card

    '''<summary>
    '''hiddf_uIdKHThe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hiddf_uIdKHThe As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cbo_Khachhang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Khachhang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txt_Mathe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Mathe As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''cbo_Loaithetichdiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Loaithetichdiem As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Date_Ngaykichhoat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Date_Ngaykichhoat As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txt_butonevent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_butonevent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Date_Ngayhethan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Date_Ngayhethan As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txt_uidKHThe_an control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_uidKHThe_an As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_AddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_AddNew As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Active control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Active As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_lock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_lock As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Delete As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lbl_Thongbao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Thongbao As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''chk_Tichdiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Tichdiem As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''txt_Sodiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Sodiem As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''radio_Tichluy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_Tichluy As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''radio_Cong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_Cong As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''radio_Tru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents radio_Tru As Global.DevExpress.Web.ASPxEditors.ASPxRadioButton

    '''<summary>
    '''txt_Noidung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Noidung As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btn_Update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Update As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Grid_Thekichhoat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_Thekichhoat As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
