'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Add_Nhanvien

    '''<summary>
    '''tblThemoinhanvien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblThemoinhanvien As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''txtManhanvien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtManhanvien As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFV_txtManhanvien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFV_txtManhanvien As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtHoten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoten As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dNgaysinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dNgaysinh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChucvu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChucvu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDiachi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiachi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuequan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuequan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDienthoai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDienthoai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REV_txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REV_txtEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtTendangnhap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTendangnhap As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMatkhau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatkhau As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMatkhau_Golai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMatkhau_Golai As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ComparePassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ComparePassword As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''chkActiveLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActiveLogin As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''dNgayvaolam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dNgayvaolam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkDanglamviec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDanglamviec As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''cmdLuu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLuu As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmdThoat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdThoat As Global.System.Web.UI.WebControls.Button
End Class
