'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WarehouseCard

    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ddlMathang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMathang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ddlKho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlKho As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''deTuNgay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deTuNgay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''deDenNgay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deDenNgay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dgvDevexpress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDevexpress As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
