'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DM_Calamviec

    '''<summary>
    '''d_Tungay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents d_Tungay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''cb_Calamviec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Calamviec As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cb_Nhanvien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Nhanvien As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txt_Ghichu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Ghichu As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Calendar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Calendar As Global.DevExpress.Web.ASPxEditors.ASPxCalendar

    '''<summary>
    '''Grid_Ca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_Ca As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
