'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PasswordChange

    '''<summary>
    '''txt_UserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_UserName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_OldPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_OldPass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NewPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewPass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NewPassRewrite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NewPassRewrite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NewPassre_Err control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewPassre_Err As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Thongbao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Thongbao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_Change control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Change As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Exit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Exit As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
