'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProcessSetup

    '''<summary>
    '''cbo_Quytrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Quytrinh As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cbo_Phongban control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Phongban As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cbo_Buoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Buoc As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''btn_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_New As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''chk_All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_All As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''Grv_Quytrinh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grv_Quytrinh As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
