'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TransferRoomHistory

    '''<summary>
    '''ltrTitleHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTitleHeader As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''Aspx_Tungay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aspx_Tungay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''Aspx_Denngay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aspx_Denngay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txt_key control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_key As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btnFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFilter As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dgvDevexpress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDevexpress As Global.DevExpress.Web.ASPxGridView.ASPxGridView
End Class
