'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageSalaries

    '''<summary>
    '''hdfuIdluongcoban control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfuIdluongcoban As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cboThang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboThang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboNam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNam As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboNhanvien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNhanvien As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboChucvu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboChucvu As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtNgaycong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgaycong As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtNgaynghi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNgaynghi As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtTienthuong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTienthuong As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtTientru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTientru As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtTamung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTamung As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''btnluuluong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnluuluong As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnXuatExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnXuatExcel As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''GrvDsluong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvDsluong As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''ExportLuong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExportLuong As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter

    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''ASPxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPanel2 As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''upKhachhang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upKhachhang As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblNhanvien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNhanvien As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''dateNgayapdung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateNgayapdung As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtLuongcoban control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLuongcoban As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtLuongngoaigio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLuongngoaigio As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtLuongtrachnhiem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLuongtrachnhiem As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtPhucap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhucap As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtGhichu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGhichu As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ltrError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrError As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ltrSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrSuccess As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnLuuLuongcoban control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLuuLuongcoban As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnLuuQTluong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLuuQTluong As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnExit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnExit As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
