'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConsultService

    '''<summary>
    '''btnQuaylai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuaylai As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ltrTitleHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrTitleHeader As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''tabDSBenhnhan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabDSBenhnhan As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''dgvDanhsachcho control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDanhsachcho As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''GrvDadieutri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvDadieutri As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''hdfuIdDichvu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfuIdDichvu As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfGiamgiaDV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfGiamgiaDV As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfTienDV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfTienDV As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dgvDevexpress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvDevexpress As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''deNgaylap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deNgaylap As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtSoPhieu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSoPhieu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtHoten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHoten As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''dgvPhieuchitiet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvPhieuchitiet As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Delete As Global.DevExpress.Web.ASPxGridView.GridViewCommandColumnCustomButton

    '''<summary>
    '''txtLidoxoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLidoxoa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLidoxoa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLidoxoa As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''ddlDMPhong control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDMPhong As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ddlTrangthai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTrangthai As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Dat_Ngaychuyen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Dat_Ngaychuyen As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnChuyen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChuyen As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIn As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Print_HD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Print_HD As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''PcThongtinKham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PcThongtinKham As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ASPxPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPanel2 As Global.DevExpress.Web.ASPxPanel.ASPxPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''memoTrieuchung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoTrieuchung As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memoYeutotangbenh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoYeutotangbenh As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memoCodia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoCodia As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memodungtanduoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memodungtanduoc As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memoDungdongduoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoDungdongduoc As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memoBenhsu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoBenhsu As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memoGhichu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoGhichu As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtMach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMach As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtHuyetap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHuyetap As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtHuyetapGio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHuyetapGio As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtLuoichat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLuoichat As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtLuoireu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLuoireu As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''cboDa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDa As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboMohoi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboMohoi As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboAn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboAn As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboNgu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNgu As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboDaitien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboDaitien As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtLandaitien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLandaitien As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lbl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtDaitienngay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDaitienngay As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''cboTieutien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTieutien As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtlantieutien control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtlantieutien As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txttieutienngay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttieutienngay As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''cboThetrang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboThetrang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtKg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtKg As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtCm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCm As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''cboTheluc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTheluc As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cboTinhthan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTinhthan As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''txtSHMGOT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSHMGOT As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtSMHGPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMHGPT As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtSHMGGT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSHMGGT As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtBiltp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBiltp As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtBiltt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBiltt As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtChol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChol As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtTriG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTriG As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtdhl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdhl As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtLdl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLdl As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtGluo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGluo As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtAuric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuric As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtCreatinin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreatinin As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''txtUre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUre As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''memoBoxung control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoBoxung As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''memoChandoantuanh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoChandoantuanh As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''GrvHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GrvHistory As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''lblKetluuan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKetluuan As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cboKetluan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboKetluan As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblPPdieutri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPPdieutri As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''memoPPDieutri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoPPDieutri As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''cb_Tinhtrangbenh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_Tinhtrangbenh As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''btnLuu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLuu As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnDieutri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDieutri As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btnKethuoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnKethuoc As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
