'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomerBirthday

    '''<summary>
    '''cbo_Ngay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Ngay As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cbo_Thang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Thang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cbo_Nam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Nam As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''cbo_Cuahang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Cuahang As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''btn_Baocao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Baocao As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_ExportExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ExportExcel As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Grid_KH_Sinhnhat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_KH_Sinhnhat As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''ASPxGridViewExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
End Class
