'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomerStatistic

    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Aspx_Tungay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aspx_Tungay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''Aspx_Denngay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Aspx_Denngay As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''chk_Nguon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Nguon As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

    '''<summary>
    '''cbo_Nguon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbo_Nguon As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''btn_Baocao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Baocao As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_ExportExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ExportExcel As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''btn_Report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Report As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Grid_Khahhang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grid_Khahhang As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''ReportToolbar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportToolbar1 As Global.DevExpress.XtraReports.Web.ReportToolbar

    '''<summary>
    '''ReportViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer1 As Global.DevExpress.XtraReports.Web.ReportViewer

    '''<summary>
    '''ASPxGridViewExporter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridViewExporter1 As Global.DevExpress.Web.ASPxGridView.Export.ASPxGridViewExporter
End Class
